###########################################################################
# 로컬 설정
###########################################################################

###########################################################################
### server 설정 
###########################################################################
server:
  port: 8080

###########################################################################
### Application 설정 
###########################################################################
application:
  # 인증완료 redirect url #
  frontend:
    scheme: http
    host: localhost
    context: 
    port: 3000

  # CORS 허용 도메인 #
  cors: 
    allowed-origin:
    - http://localhost:3000

###########################################################################
### Spring 설정 
###########################################################################
spring:
  ### Redis 설정 ###
  data:
    redis:
      host: 192.168.50.210
      port: 6379

  ### Datasource 설정 ###
  r2dbc:
    url: r2dbc:postgresql://192.168.50.210:5432/home
    username: admin
    password: admin
    properties:
      schema: public

  ### 보안 설정 ###
  security:
    ### OIDC 연동 설정 ###
    oauth2:
      client:
        provider:
          fennex:
            issuer-uri: http://192.168.50.210:8040/realms/${spring.application.realm}
            jwk-set-uri: http://192.168.50.210:8040/realms/${spring.application.realm}/protocol/openid-connect/certs
        registration:
          fennex:
            client-id: dev-client
            client-secret: FN9eR0m03Hwza0TanEHDA8Px7pJop5ly

    ### 비로그인 백엔드 설정 ###
    access:
      nologin:
      - /translate/**

###########################################################################
### Router data 설정 
###########################################################################
routers:
  defaults:
    translate:
      context: translate
      scheme: http
      host: localhost
      port: 9090
    template:
      context: template
      scheme: http
      host: localhost
      port: 9090
    movie:
      context: movie
      scheme: http
      host: localhost
      port: 9090

###########################################################################
### Logging 설정 
###########################################################################
logging:
  level:
    root: info